version: '3.8'
services:
  apisix:
    image: "apache/apisix:2.10.5-alpine"
    volumes:
      - ./data/apisix/apisix_log:/usr/local/apisix/logs
      - ./data/apisix/apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
    networks:
      - apisix
      - backend

  dashboard:
    image: "apache/apisix-dashboard:2.11-alpine"
    volumes:
      - ./data/apisix-dashboard/dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9000:9000/tcp"
    networks:
      - apisix

  etcd:
    image: bitnami/etcd:3.4.9
    user: root
    volumes:
      - ./data/etcd:/etcd_data
    environment:
      ETCD_DATA_DIR: /etcd_data
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      - apisix
  
  postgres:
    image: postgres:14.2-alpine3.15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    networks:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:17.0.1
    command: start-dev
    environment:
      KC_HTTP_PORT: 8180
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: bachhs.me
      KC_HOSTNAME_STRICT: false
    ports:
      - 8180:8180
    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - keycloak
      - backend

networks:
  apisix:
    driver: bridge
  keycloak:
    driver: bridge
  backend:
    driver: bridge